- hosts: 192.168.50.5
  tasks:
  - name: login to dockerhub
    docker_login:
      username: mayupdocker
      password: mayuresh11
      email: vicky.pardeshi@gmail.com

  #- name: pull image from dockerhub
  #  docker_image:
  #    name: mayupdocker/mynodeapp
  #    tag: {{ tag }}

  - name: start container
    docker_container:
      name: mynodeapp
      image: mayupdocker/nodeapp:{{ tag }}
      published_ports: 8080:3000
